server:
  restart: "always"
  image: "sahsu/docker-munin-server"
  ports: 
    - "80:80"
  links: 
    - munin-node
  environment:
   NODES: "munin-node:munin-node"
   GROUP: "PERF"
  volumes:
   - "/var/lib/munin:/data/var/lib/munin"
   - "/var/log/munin"
   - "/var/cache/munin:/data/cache/munin"
   - "/var/www/munin:/data/var/www/munin"
munin-node:
  restart: "always"
  image: "sahsu/docker-munin-node"
  environment:
   ALLOW: "cidr_allow 0.0.0.0/0"
  privileged: true
#  net: "host"
